### ISSUE TITLE
Query about stripping sub prompts in inf-janet.el

### ISSUE THREAD

**Issue by sogaiu** [mpwillson/emacs#1]
Sorry, this isn't an issue per se, more of an inquiry.  Hope that's ok.

I'm curious whether you've encountered any difficulties with the `comint-preoutput-filter-functions` and `janet-strip-prompt` approach - ([this bit](https://github.com/mpwillson/emacs/blob/3415ec3fe6342984fc26fbda00172a569c228f3d/inf-janet.el#L276)).

The sub-prompts showing up have long been something I've wanted to do something about but I didn't go through with the `comint-preoutput-filter-functions` approach because of two cases that it might not work with:

1. IIUC, output to filters can come split up [1] 
2. It seemed possible there might be cases where sub-prompts would be indistinguishable from non-sub-prompt information

Perhaps these are mistaken concerns or may be in practice they don't tend to arise.

Anyway, thanks for your `inf-janet.el`, it seems quite nice!

P.S. I've mentioned your `inf-janet` implementation [here](https://github.com/sogaiu/janet-editor-and-tooling-info/blob/09d6c0229d1e6817c420af839f3926a1008b329e/doc/emacs.md#stdio-based-repl).

---

[1] From "Process Filter Functions:

> The output to the filter may come in chunks of any size. A program that produces the same output twice in a row may send it as one batch of 200 characters one time, and five batches of 40 characters the next. If the filter looks for certain text strings in the subprocess output, make sure to handle the case where one of these strings is split across two or more batches of output; one way to do this is to insert the received text into a temporary buffer, which can then be searched. 

Wasn't too keen on the temporary buffer work-around mentioned above (^^;

**Comment by mpwillson** [comment]
Hi Sogaiu,

You've clearly read the elisp documentation way more closely than
I did!.

I have yet to encounter an issue related to the chunking of
filter output or stripping strings that aren't prompts. However,
that doesn't mean it can't happen. I'll have to revisit the code
if a problem does manifest itself.

Thanks very much for the acknowlegement and the mention.

Cheers,
Mark
